#SECE: {} # See user-config.yml
version:
    upstream:
        # const int SE_VERSION = 01146006;
        regex: 'const int SE_VERSION = (?P<version>[0-9]+);'
        # F:\Projects\SpaceEngineers-CE\Sources\SpaceEngineers.Game\SpaceEngineersGame.cs
        file: Sources/SpaceEngineers.Game/SpaceEngineersGame.cs
        type: ksh
    sece:
        # const int SE_VERSION = 01146006;
        regex: 'const int SECE_BUILD = (?P<version>[0-9]+);'
        # F:\Projects\SpaceEngineers-CE\Sources\SpaceEngineers.Game\SpaceEngineersGame.cs
        file: Sources/SpaceEngineers.Game/SpaceEngineersGame.cs
        type: intver
reference-fixes:
    - HavokWrapper
    # Only used on XB1.
    #- RakNet
    - SharpDX
    - SharpDX.D3DCompiler
    - SharpDX.DXGI
    - SharpDX.Desktop
    - SharpDX.Direct2D1
    - SharpDX.Direct3D11
    - SharpDX.Direct3D9
    - SharpDX.DirectInput
    - SharpDX.Mathematics
    - SharpDX.Toolkit
    - SharpDX.XAudio2
    - SteamSDK
    - VRage.Native
    - RecastDetourWrapper
    # Roslyn shit.
    - Microsoft.CodeAnalysis
    - Microsoft.CodeAnalysis.CSharp
    - System.Collections.Immutable
    - System.Reflection.Metadata
